### ISSUE TITLE
Integrate an easy way to configure our hardware and ROS nodes

### ISSUE THREAD

**Issue by jjrbfi** [rokokoo/hal_core#1]
The principal idea is to have a YAML file with our configuration:

1. Actual Beckhoff EtherCAT **hardware** configuration.
2. Remap component Pins as for example: **lcec.0.2.din-6-not** to **R_switch**.

I will attach images with our actual EtherCAT configuration in our iICM robot:

![image](https://user-images.githubusercontent.com/71790456/136168827-d6822039-626c-46d4-80bb-3c26775711e7.png)

**Comment by jjrbfi** [comment]
This is an example that how will look the YAML file with the config we have on mind.

```yaml
ETHERCAT:
  MASTERIDX:  '0'
  APPTIMEPERIOD:  '1000000'
  REFCLOCKSYNCCYCLES:  '-1'
  EK1100:
  - EL1008
  - EL1008
  - EL1008
  - EL1008
  - EL2008
  - EL2008
  - EL7342
  - EL7342
  - EL9576
  - EL6900
  - EL1904
  - EL2904
  - EL9505

REMAP:
  lcec.0.7.srv-0-cmd:  'cmd_motor_1.7'
  lcec.0.7.srv-1-cmd:  'cmd_motor_2.7'
  lcec.0.8.srv-0-enable:  'status_motor_1.8'
  lcec.0.8.srv-1-enable:  'status_motor_2.8'
  lcec.0.2.din-6-not:  'R_swtich'
  lcec.0.2.din-4-not:  'L_switch'
```


With remap we are having just all that we want to be listed on ROS topics. @gurnarok

**Comment by jjrbfi** [comment]
As quick found I got, seems like we have to get the values from pdo values from each terminal file document in order to "remap" the output directly in the **ethercat-conf.xml** as I saw in this [example](https://forum.linuxcnc.org/forum/search?query=halpin&childforums=1&catids=81):

![image](https://user-images.githubusercontent.com/71790456/136339349-c62db7da-dc3a-4698-a07e-e9bd5cc56d29.png)

Isn't hard to get those values and work on it but if we are going to create a script that made those will be a bit tricky maybe to iterate in this kind of [.xml files](https://download.beckhoff.com/download/configuration-files/io/ethercat/xml-device-description/Beckhoff_EtherCAT_XML.zip).

I'm waiting if got some more information to know if we can remap the port without doing in that way.

@gurnarok

**Comment by jjrbfi** [comment]
I just found a way to rename the _terminal name_, not the whole pin name directly from the .xml file.

![image](https://user-images.githubusercontent.com/71790456/136534316-6fbd0b38-6b8f-4ca1-8332-f130cd30fd2f.png)

Looks like this:
![image](https://user-images.githubusercontent.com/71790456/136534068-d593046c-b763-47dc-ae38-b65355fd8374.png)

How that looks to you? @gurnarok

**Comment by gurnarok** [comment]
We could use this with the YAML file, creating something like this:

```yaml
ETHERCAT:
  MASTERIDX:  0
  APPTIMEPERIOD:  1000000
  REFCLOCKSYNCCYCLES:  -1
  SLAVES:
  - EK1100
  - EL1008
  - EL1008
  - EL1008
  - EL1008
  - EL2008
  - EL2008
  - EL7342: {name: 'motor1'}
  - EL7342: {name: 'motor2'}
  - EL9576
  - EL6900
  - EL1904
  - EL2904
  - EL9505
```

I could create XML file with named parts
